version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-ligas-bsk
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=liga
      - JWT_SECRET=251099thiago
    networks:
      - app-network
  db:
    container_name: go-ligas-bsk-db
    image: postgres:12
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: liga
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  pgdata: {}
